import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#0e0e11",
        "surface-container-lowest": "#000000",
        "surface": "#0e0e11",
        "background": "#0e0e11",
        "surface-container-low": "#131317",
        "surface-container": "#19191e",
        "surface-container-high": "#1e1f26",
        "surface-container-highest": "#24252d",
        "surface-bright": "#2a2b35",
        "surface-variant": "#24252d",
        "on-surface": "#e6e4ef",
        "on-surface-variant": "#abaab4",
        "on-background": "#e6e4ef",
        "primary": "#c6c6c9",
        "primary-dim": "#b8b8bb",
        "primary-fixed": "#e2e2e5",
        "primary-fixed-dim": "#d4d4d7",
        "primary-container": "#454749",
        "on-primary": "#3f4043",
        "on-primary-fixed": "#3e3f42",
        "on-primary-fixed-variant": "#5a5b5e",
        "on-primary-container": "#d0d0d3",
        "secondary": "#9d9da6",
        "secondary-dim": "#9d9da6",
        "secondary-container": "#3a3b43",
        "secondary-fixed": "#e3e1ec",
        "secondary-fixed-dim": "#d4d3dd",
        "on-secondary": "#1f2027",
        "on-secondary-fixed": "#3e3f47",
        "on-secondary-fixed-variant": "#5a5b63",
        "on-secondary-container": "#bfbec8",
        "tertiary": "#f9f9fd",
        "tertiary-dim": "#ebebef",
        "tertiary-container": "#ebebef",
        "tertiary-fixed": "#f3f3f7",
        "tertiary-fixed-dim": "#e5e5e9",
        "on-tertiary": "#5e5f62",
        "on-tertiary-container": "#55575a",
        "on-tertiary-fixed": "#484a4d",
        "on-tertiary-fixed-variant": "#65666a",
        "outline": "#75757e",
        "outline-variant": "#474750",
        "inverse-surface": "#fbf8fc",
        "inverse-on-surface": "#555458",
        "inverse-primary": "#5e5f62",
        "surface-tint": "#c6c6c9",
        "error": "#ec7c8a",
        "error-dim": "#b95463",
        "error-container": "#7f2737",
        "on-error": "#490013",
        "on-error-container": "#ff97a3",
        "warn": "#d97706",
        "ok": "#10b981",
        "accent": "#E4E4E7",
        "accent-fg": "#0A0A0A",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        sans: ["Geist", "system-ui", "sans-serif"],
        mono: ["Geist Mono", "monospace"],
      },
      keyframes: {
        "dot-bounce": {
          "0%, 60%, 100%": { transform: "translateY(0)",    opacity: "0.45" },
          "30%":            { transform: "translateY(-5px)", opacity: "1"    },
        },
      },
      animation: {
        "dot-bounce": "dot-bounce 1.1s ease-in-out infinite",
      },
    },
  },
  plugins: [],
} satisfies Config;
