use tauri::State;
use uuid::Uuid;

use crate::db::models;
use crate::workspace::state::ActiveWorkspace;

fn ire_dir(active: &State<'_, ActiveWorkspace>) -> Result<std::path::PathBuf, String> {
    let guard = active.0.lock().map_err(|e| e.to_string())?;
    let handle = guard.as_ref().ok_or("no workspace open")?;
    Ok(handle.state.path.join(".ire"))
}

/// Save the current tab's messages as a completed chat session.
/// `session_uuid` — stable UUID generated by the frontend for the lifetime of the tab
/// session. Passing the same UUID on subsequent calls upserts the row so the session
/// stays current without creating duplicates.
#[tauri::command]
pub fn chat_history_save(
    active: State<'_, ActiveWorkspace>,
    session_uuid: Option<String>,
    tab_label: String,
    provider: String,
    model: String,
    started_at: String,
    messages_json: String,
) -> Result<(), String> {
    let dir = ire_dir(&active)?;
    let session_uuid = session_uuid.unwrap_or_else(|| Uuid::new_v4().to_string());
    let ended_at = chrono::Local::now().to_rfc3339();

    // Parse minimally to extract count and first user message.
    let msgs: Vec<serde_json::Value> =
        serde_json::from_str(&messages_json).unwrap_or_default();
    let message_count = msgs.len() as i64;

    // Skip saving empty sessions.
    if message_count == 0 {
        return Ok(());
    }

    let first_user_msg: Option<String> = msgs
        .iter()
        .find(|m| m.get("role").and_then(|r| r.as_str()) == Some("user"))
        .and_then(|m| m.get("text").and_then(|t| t.as_str()))
        .map(|t| t.chars().take(120).collect());

    models::insert_chat_session(
        &dir,
        &session_uuid,
        &tab_label,
        &provider,
        &model,
        &started_at,
        &ended_at,
        message_count,
        first_user_msg.as_deref(),
        &messages_json,
    )
    .map_err(|e| e.to_string())
}

/// List past chat sessions (summary only — no messages blob).
#[tauri::command]
pub fn chat_history_list(
    active: State<'_, ActiveWorkspace>,
    limit: Option<u32>,
) -> Result<Vec<models::ChatSessionRow>, String> {
    let dir = ire_dir(&active)?;
    models::list_chat_sessions(&dir, limit.unwrap_or(50) as usize)
        .map_err(|e| e.to_string())
}

/// Return the full `messages_json` blob for a single session.
#[tauri::command]
pub fn chat_history_get(
    active: State<'_, ActiveWorkspace>,
    session_uuid: String,
) -> Result<Option<String>, String> {
    let dir = ire_dir(&active)?;
    models::get_chat_session_messages(&dir, &session_uuid)
        .map_err(|e| e.to_string())
}

/// Permanently delete a chat session.
#[tauri::command]
pub fn chat_history_delete(
    active: State<'_, ActiveWorkspace>,
    session_uuid: String,
) -> Result<(), String> {
    let dir = ire_dir(&active)?;
    models::delete_chat_session(&dir, &session_uuid)
        .map_err(|e| e.to_string())
}
