use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{anyhow, Context, Result};
use chrono::Local;

const SCHEMA_MD: &str = include_str!("../../assets/seed/_schema.md");
const PULSE_MD: &str = include_str!("../../assets/seed/pulse.md");
const LONG_TERM_MD: &str = include_str!("../../assets/seed/long-term.md");
const FAILURES_MD: &str = include_str!("../../assets/seed/failures.md");

const GITIGNORE_ENTRIES: &[&str] = &[
    ".ire/.lock",
    ".ire/local.db",
    ".ire/logs/",
    ".ire/workspace.json",
    ".ire/experiments/",
    ".ire/cache/",
];

/// Validate that `path` is an existing IRE workspace.
pub fn validate_existing(path: &Path) -> Result<()> {
    if !path.is_dir() {
        return Err(anyhow!("not a directory: {}", path.display()));
    }
    if !path.join(".git").exists() {
        return Err(anyhow!("not a git repository: {}", path.display()));
    }
    let marker = path.join(".ire/wiki/_schema.md");
    if !marker.exists() {
        return Err(anyhow!(
            "missing .ire/wiki/_schema.md — not an IRE workspace"
        ));
    }
    Ok(())
}

/// Scaffold a fresh `.ire/` tree, seed wiki, gitignore, and git-init if needed.
/// Idempotent: existing files are not overwritten.
pub fn initialize(path: &Path) -> Result<()> {
    if !path.is_dir() {
        return Err(anyhow!("not a directory: {}", path.display()));
    }

    // git init if absent
    if !path.join(".git").exists() {
        run_git(path, &["init", "--quiet"])?;
    }

    let ire = path.join(".ire");
    let wiki = ire.join("wiki");
    let status = wiki.join("status");
    let short_term = status.join("short-term");
    let resources = wiki.join("resources");
    let logs = ire.join("logs");
    let experiments = ire.join("experiments");
    let cache = ire.join("cache");

    for d in [&ire, &wiki, &status, &short_term, &resources, &logs, &experiments, &cache] {
        fs::create_dir_all(d).with_context(|| format!("create {}", d.display()))?;
    }

    write_if_absent(&wiki.join("_schema.md"), SCHEMA_MD)?;
    write_if_absent(&wiki.join("notes.md"), "")?;
    write_if_absent(&wiki.join("ideas.md"), "")?;
    write_if_absent(&wiki.join("log.md"), &log_seed())?;
    write_if_absent(&status.join("pulse.md"), PULSE_MD)?;
    write_if_absent(&status.join("long-term.md"), LONG_TERM_MD)?;
    write_if_absent(&status.join("failures.md"), FAILURES_MD)?;
    // _index.md is regenerated by the wiki layer in Phase 2; seed a placeholder.
    write_if_absent(&wiki.join("_index.md"), &index_seed())?;

    ensure_gitignore(path)?;
    initial_commit_if_empty(path)?;
    Ok(())
}

fn write_if_absent(p: &Path, content: &str) -> Result<()> {
    if p.exists() {
        return Ok(());
    }
    let mut f = fs::File::create(p).with_context(|| format!("create {}", p.display()))?;
    f.write_all(content.as_bytes())?;
    f.sync_all()?;
    Ok(())
}

fn log_seed() -> String {
    let now = Local::now().format("%Y-%m-%d %H:%M");
    format!("## [{now}] init | workspace scaffolded\n")
}

fn index_seed() -> String {
    "- [_schema.md](./_schema.md) — wiki conventions for the agent\n\
     - [notes.md](./notes.md) — running user notes\n\
     - [ideas.md](./ideas.md) — running user ideas\n\
     - [log.md](./log.md) — append-only operation log\n\
     - [status/pulse.md](./status/pulse.md) — current research question + blocker + focus\n\
     - [status/long-term.md](./status/long-term.md) — architectural decisions and pivots\n\
     - [status/failures.md](./status/failures.md) — methods that did not work\n"
        .to_string()
}

fn ensure_gitignore(path: &Path) -> Result<()> {
    let gi = path.join(".gitignore");
    let existing = if gi.exists() {
        fs::read_to_string(&gi)?
    } else {
        String::new()
    };
    let mut out = existing.clone();
    let mut added = false;
    for entry in GITIGNORE_ENTRIES {
        if !line_present(&existing, entry) {
            if !out.ends_with('\n') && !out.is_empty() {
                out.push('\n');
            }
            if !added {
                out.push_str("\n# IRE\n");
                added = true;
            }
            out.push_str(entry);
            out.push('\n');
        }
    }
    if added || !gi.exists() {
        fs::write(&gi, out).with_context(|| format!("write {}", gi.display()))?;
    }
    Ok(())
}

fn line_present(haystack: &str, needle: &str) -> bool {
    haystack.lines().any(|l| l.trim() == needle)
}

fn initial_commit_if_empty(path: &Path) -> Result<()> {
    // If there is no HEAD yet, we make an initial commit. Otherwise leave
    // the user's history untouched.
    let head = Command::new("git")
        .args(["rev-parse", "--verify", "HEAD"])
        .current_dir(path)
        .output()?;
    if head.status.success() {
        return Ok(());
    }
    run_git(path, &["add", ".gitignore", ".ire/wiki"])?;
    run_git(path, &["commit", "-m", "Initialize IRE workspace", "--quiet"])?;
    Ok(())
}

fn run_git(cwd: &Path, args: &[&str]) -> Result<()> {
    let out = Command::new("git").args(args).current_dir(cwd).output()?;
    if !out.status.success() {
        return Err(anyhow!(
            "git {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    Ok(())
}

pub fn ire_dir(path: &Path) -> PathBuf {
    path.join(".ire")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn git_available() -> bool {
        Command::new("git")
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    }

    #[test]
    fn initialize_scaffolds_full_tree() {
        if !git_available() {
            eprintln!("skipping: git not available");
            return;
        }
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();

        initialize(root).unwrap();

        for rel in [
            ".git",
            ".ire/wiki/_schema.md",
            ".ire/wiki/_index.md",
            ".ire/wiki/notes.md",
            ".ire/wiki/ideas.md",
            ".ire/wiki/log.md",
            ".ire/wiki/status/pulse.md",
            ".ire/wiki/status/long-term.md",
            ".ire/wiki/status/failures.md",
            ".ire/wiki/status/short-term",
            ".ire/wiki/resources",
            ".ire/logs",
            ".ire/experiments",
            ".ire/cache",
            ".gitignore",
        ] {
            assert!(root.join(rel).exists(), "missing {rel}");
        }

        let gitignore = fs::read_to_string(root.join(".gitignore")).unwrap();
        for entry in GITIGNORE_ENTRIES {
            assert!(
                gitignore.lines().any(|l| l.trim() == *entry),
                "gitignore missing {entry}"
            );
        }

        validate_existing(root).unwrap();

        // Idempotent re-run.
        initialize(root).unwrap();

        // Custom user content survives re-init.
        let notes = root.join(".ire/wiki/notes.md");
        fs::write(&notes, "user data").unwrap();
        initialize(root).unwrap();
        assert_eq!(fs::read_to_string(&notes).unwrap(), "user data");
    }

    #[test]
    fn gitignore_dedupe_appends_only_missing_entries() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        fs::write(root.join(".gitignore"), ".ire/.lock\nnode_modules\n").unwrap();
        ensure_gitignore(root).unwrap();
        let after = fs::read_to_string(root.join(".gitignore")).unwrap();
        assert_eq!(after.matches(".ire/.lock").count(), 1);
        assert!(after.contains("node_modules"));
        assert!(after.contains(".ire/local.db"));
    }
}
