name: Dev build

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"

concurrency:
  group: dev-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      release: false
    secrets: inherit
